config/routes.rb
EsLw::Application.routes.draw do
  resources :articles

  root 'articles#index'

  get 'search_boolean' => 'articles#search_boolean'

end

app/models/article.rb
class Article < ActiveRecord::Base
  after_save :add_document
  after_destroy :remove_document

  acts_as_taggable

  def add_document
    index = Tire.index 'articles'
    index.store type: self.class.name.downcase, id: id, title: title,
      tags: tag_list, created_at: created_at, content: content
  end

  def remove_document
    Tire.index('articles').remove(self.class.name.downcase, id)
  end

  def self.search(params)
    s = Tire.search 'articles' do
          query do
            string "title:#{params[:query]}" if params[:query].present?
          end

          filter :terms, :tags => params[:filter_tags].split(',') if params[:filter_tags].present?

          facet 'global-tags', :global => true do
            terms :tags
          end

          facet 'current-tags' do
            terms :tags
          end
        end
  end

  def self.search_boolean(params)
    s = Tire.search 'articles' do
          query do
            boolean do
              should   { string "tags:#{params[:should]}" } if params[:should].present?
              must_not { string "tags:#{params[:must_not]}" } if params[:must_not].present?
            end
          end

          facet 'global-tags', :global => true do
            terms :tags
          end

          facet 'current-tags' do
            terms :tags
          end
        end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:query].present?
      @articles = Article.search(params).results
    else
      @articles = Article.all
    end
  end

  def search_boolean
    @articles = Article.search_boolean(params).results

    render 'index'
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= form_tag articles_path, method: :get do %>
  <p>
    <%= label_tag :query %>
    <%= text_field_tag :query, params[:query] %>
    <%= label_tag :filter_tags %>
    <%= text_field_tag :filter_tags, params[:filter_tags] %>

    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<%= form_tag search_boolean_path, method: :get do %>
  <p>
    <%= label_tag :should %>
    <%= text_field_tag :should, params[:should] %>
    <%= label_tag :must_not %>
    <%= text_field_tag :must_not, params[:must_not] %>

    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<h2>current-tags</h2>
<ul>
  <% if @articles.class == Tire::Results::Collection %>
    <% @articles.facets['current-tags']['terms'].each do |f|  %>
        <li><%= "#{f['term'].ljust(10)} #{f['count']}" %></li>
    <% end -%>
  <% end -%>
</ul>
<h2>global-tags</h2>
<ul>
  <% if @articles.class == Tire::Results::Collection %>
    <% @articles.facets['global-tags']['terms'].each do |f|  %>
        <li><%= "#{f['term'].ljust(10)} #{f['count']}" %></li>
    <% end -%>
  <% end -%>
</ul>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td>Tags: <%= article.tag_list || article.tags %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @article.tag_list %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EsLw</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>